# Generated by Django 5.1.3 on 2024-11-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_tittle_task_title_alter_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='tittle',
        ),
    ]
